export const interiorDesignContent = {
  hero: {
    eyebrow: 'THIẾT KẾ NỘI THẤT',
    title: 'Thiết Kế Nội Thất Cao Cấp',
    subtitle: 'Nhà Phố · Biệt Thự · Căn Hộ',
    description:
      'Kiến tạo không gian sống đẳng cấp với thiết kế 3D chân thực, vật liệu sang trọng và giải pháp cá nhân hóa theo phong cách riêng của mỗi gia chủ.',
  },

  intro: {
    eyebrow: 'VỀ DỊCH VỤ',
    title: 'Thiết Kế Nội Thất Nhà Phố – Biệt Thự',
    paragraphs: [
      'Tại Human Interior, chúng tôi mang đến giải pháp thiết kế nội thất trọn gói – từ ý tưởng ban đầu đến bản vẽ 3D hoàn chỉnh. Mỗi dự án được chạm khắc tỉ mỉ, tối ưu không gian sống và phản ánh cá tính riêng của gia chủ.',
      'Với đội ngũ kiến trúc sư giàu kinh nghiệm cùng hệ thống công nghệ 3D tiên tiến, chúng tôi cam kết mang đến những bản thiết kế chân thực đến từng chi tiết, giúp khách hàng hình dung trọn vẹn ngôi nhà mơ ước trước khi thi công.',
    ],
    highlights: [
      { number: '500+', label: 'Dự án hoàn thành' },
      { number: '15+', label: 'Năm kinh nghiệm' },
      { number: '100%', label: 'Cam kết chất lượng' },
      { number: '24/7', label: 'Hỗ trợ tư vấn' },
    ],
  },

  categories: [
    { id: 'all', label: 'Tất cả' },
    { id: 'nha-pho', label: 'Nhà phố' },
    { id: 'biet-thu', label: 'Biệt thự' },
    { id: 'can-ho', label: 'Căn hộ' },
  ],

  projects: [
    {
      id: 1,
      category: 'nha-pho',
      title: 'Thiết kế nội thất nhà phố 1 trệt 2 lầu',
      location: 'Park Riverside Phú Hữu – Thủ Đức',
      area: '220m²',
      style: 'Hiện đại',
      image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb3?w=800&q=80',
    },
    {
      id: 2,
      category: 'nha-pho',
      title: 'Thiết kế nội thất nhà phố 1 trệt 1 lầu',
      location: 'NovaWorld Hồ Tràm',
      area: '140m²',
      style: 'Tân cổ điển',
      image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    },
    {
      id: 3,
      category: 'nha-pho',
      title: 'Thiết kế nội thất nhà phố 4 phòng ngủ',
      location: 'Bình Thạnh',
      area: '268m²',
      style: 'Hiện đại',
      image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    },
    {
      id: 4,
      category: 'nha-pho',
      title: 'Thiết kế nội thất nhà phố 3 phòng ngủ',
      location: 'Thủ Đức',
      area: '230m²',
      style: 'Tân cổ điển',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    },
    {
      id: 5,
      category: 'nha-pho',
      title: 'Thiết kế nội thất nhà phố 320m²',
      location: 'Thủ Đức',
      area: '320m²',
      style: 'Hiện đại',
      image: 'https://images.unsplash.com/photo-1600573472591-ee6981cf81d6?w=800&q=80',
    },
    {
      id: 6,
      category: 'nha-pho',
      title: 'Thiết kế nội thất nhà phố liền kề',
      location: 'Phố Đông Village',
      area: '220m²',
      style: 'Hiện đại',
      image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
    },
    {
      id: 7,
      category: 'biet-thu',
      title: 'Thiết kế nội thất Villa 270m²',
      location: 'Phú Quốc',
      area: '270m²',
      style: 'Hiện đại',
      image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80',
    },
    {
      id: 8,
      category: 'biet-thu',
      title: 'Thiết kế nội thất Biệt thự song lập',
      location: 'Quận 2',
      area: '350m²',
      style: 'Luxury',
      image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
    },
    {
      id: 9,
      category: 'can-ho',
      title: 'Nội thất căn hộ The Beverly Solari',
      location: 'Vinhomes Grand Park',
      area: '69m²',
      style: 'Hiện đại',
      image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    },
    {
      id: 10,
      category: 'can-ho',
      title: 'Nội thất căn hộ Opus One 80m²',
      location: 'Thủ Đức',
      area: '80m²',
      style: 'Minimalist',
      image: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80',
    },
    {
      id: 11,
      category: 'can-ho',
      title: 'Nội thất căn hộ Vinhome Grand Park',
      location: 'TP. Thủ Đức',
      area: '103m²',
      style: 'Hiện đại',
      image: 'https://images.unsplash.com/photo-1600210491369-e753d80a41f3?w=800&q=80',
    },
    {
      id: 12,
      category: 'biet-thu',
      title: 'Thiết kế nội thất nhà phố 340m²',
      location: 'Quận 12',
      area: '340m²',
      style: 'Hiện đại',
      image: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80',
    },
  ],

  cta: {
    title: 'Bắt Đầu Dự Án Của Bạn',
    description:
      'Liên hệ ngay để được tư vấn miễn phí và nhận báo giá thiết kế nội thất theo nhu cầu.',
    buttonText: 'Liên Hệ Tư Vấn',
    buttonHref: '/contact',
  },
} as const
